### PR TITLE
L10n fr

### PR DESCRIPTION
**Pull request by tdd**
Hey Tim!

First, gratz on this cool workshop.

As part of the nodeschool/organizers#64 g11n effort currently underway, I'm bringing all workshopper-based workshops up to snuff on the latest versions of it so they can get translated (L10n) readily.

I'm also bringing them on the latest versions of their tested libs, and re-testing all the exercises, to reduce the risk of obsolescence.

This PR both upgrades the infra and provides FR L10n with third-party proofreading already baked in. I hope you see this favorably. We're hosting regular Paris NodeSchool sessions, and it would be fantastic if this could all be merged in and bumped in npm soon :smile:

I am, of course, available for all questions and discussions on this.

Best,

### CODE REVIEW

**Comment by timoxley** [comment]
Oh wow. Thank you.

**Comment by timoxley** [comment]
[Released as 1.0.0](https://github.com/timoxley/functional-javascript-workshop/compare/0.0.28...1.0.0)

**Comment by timoxley** [comment]
Thanks again! Amazing work.

**Comment by tdd** [comment]
Hey Tim,

Glad you liked it! Thanks for the merge and version bump!

**Comment by timoxley** [comment]
:heart:

**Pull request merged**
